language: python
python:
  - 2.7

sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=1.9.6
#  - ANSIBLE_VERSION=2.0.2.0
#  - ANSIBLE_VERSION=2.0.0.2

install:
  - pip install -r requirements.txt
  - pip install -q ansible==$ANSIBLE_VERSION
## Create module package and install it at the same level as the project
  - cd ..
  - tar -czf Juniper.junos ansible-junos-stdlib
  - mkdir tmp
  - mv Juniper.junos tmp/
  - cd tmp
  - ansible-galaxy install -p ../ Juniper.junos
  - cd ../ansible-junos-stdlib/tests
## Install Virtualbox
  - sudo apt-get update -q
  - sudo apt-get install -y linux-headers-$(uname -r)
  - sudo apt-get install -q virtualbox --fix-missing
  - VBoxManage --version

## Install Vagrant
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - vagrant plugin install vagrant-junos
  - vagrant plugin install vagrant-host-shell
  - vagrant up

script:
  - ansible-playbook junos_ping/pb.junos_ping.yaml
  - ansible-playbook junos_get_facts/pb.junos_get_facts.yaml
