language: python
python:
  - 2.7

sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=2.2.0.0

install:
  - cd tests
  - pip install -r requirements.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - ansible-galaxy install Juniper.junos -p ./roles
  - pip install ansible junos-eznc lxml jxmlease markupsafe requests httplib2
  - mkdir library
  - git clone https://github.com/Juniper/ravello-ansible.git library/ravello-ansible
  - mv .travis_ansible_python.yaml group_vars/all/travis_ansible_python.yaml
## start Junos VM
  - ansible-playbook -i ravello.ini pb.rav.token.create-deploy.yaml
  - ansible-playbook -i ravello.ini pb.rav.token.fqdn_get.yaml
  - ansible-playbook -i ravello.ini pb.junos_ping.yaml

script:
  - ansible-playbook junos_ping/pb.junos_ping.yaml
  - ansible-playbook junos_get_facts/pb.junos_get_facts.yaml
