---
- name: Creating Junos NOOB conf
  template: src={{ noob_conf }} dest='{{ destdir }}/{{inventory_hostname}}-noob.conf'
  register: noob_conf
  tags:
    - noob

- name: Push Junos NOOB conf to device
  junos_noob_config:
    name={{ inventory_hostname }}
    port='-t{{termserver}},{{ts_port}}'
    file={{ noob_conf.dest|default(noob_conf.path) }}
    logfile={{ logfile }}
    savedir={{ savedir }}
    passwd={{ passwd }}
  when: force is defined or noob_conf.changed
  tags:
    - noob
